Feat/postgresql setup
nuyiep/42KL-23-Ft_Transcendence pull request #36
Opened 2024-09-13 16:37 UTC by rsoo23

Added the postgresql + pgadmin setup via docker compose

**PGAdmin Setup**
1. set .env vars: (DB_HOST is not required) (the values below can be changed afaik)
DB_NAME=chroma_db
DB_USER=root 
DB_PASSWORD=root
DB_PORT=5432

PGADMIN_DEFAULT_EMAIL=
PGADMIN_DEFAULT_PASSWORD=

2. run make to build and start containers
3. run docker inspect transcendence-postgresql-1
4. find the value of IPAddress and save it
5. go to your browser and enter localhost:5050
6. enter your credentials from the PGADMIN vars in your .env
7. click add new server
8. name: can put any name
9. go to connections:
Hostname / address: enter the ip address you saved just now
username, password: enter DB_USER and DB_PASSWORD
10. go to Servers -> {name of db} -> Databases, right click and then create -> database
11. Database entry has to match DB_NAME

12. go to backend dir and run ./devrunsh makemigrations + migrate

2024-09-18 07:02 UTC, dastrukar requested changes

2024-09-18 07:02 UTC, dastrukar commented on docker-compose.yml
> +    ports:
?
why not use use docker networks instead of exposing postgresql's port?

2024-09-18 07:02 UTC, dastrukar commented on backend/requirements.txt
> -channels-redis==4.2.0
...i think you accidentally removed a module
also, idk if this is generated via pip, but personally i just manually add the dependency and update my python environment (to prevent adding a bunch of dependencies from the modules)

2024-09-18 07:02 UTC, dastrukar commented on backend/main/settings.py
> +        'PORT': getenv_and_validate('DB_PORT'),
do you mind if i made a commit to let DEBUG mode use SQLite3 database? so that we don't have to run docker for the database to work while in-development
(could add a different variable if that's problematic, maybe like `DEBUG_USE_SQLITE3`)

2024-09-18 07:27 UTC, rsoo23 commented on backend/main/settings.py
> +        'PORT': getenv_and_validate('DB_PORT'),
sure

2024-09-22 06:20 UTC, dastrukar approved these changes

2024-09-22 06:20 UTC, merged